### ISSUE TITLE
GPU memory requirements and training time

### ISSUE THREAD

**Issue by michelle1223** [Yueeeeeeee/LlamaRec#3]
Hi,

May I ask what GPUs were used for training the ranker model (train_ranker.py)?

I'm currently trying to train this model on the MovieLens 1M dataset on Colab with A100 GPU, but it seems to take a very long time like below (approximately 80 hours). So I was wondering if I was doing something wrong or it's supposed to be like this. If you don't mind, could you let me know what computational resources were used and how much time it took for training?

```
{'loss': 6.2229, 'grad_norm': 21.462696075439453, 'learning_rate': 1e-05, 'epoch': 0.0}
{'loss': 5.3854, 'grad_norm': 22.489585876464844, 'learning_rate': 2e-05, 'epoch': 0.0}
  0% 29/61344 [02:20<80:12:38,  4.71s/it]Traceback (most recent call last):
```

Thanks for your work!

**Comment by Yueeeeeeee** [comment]
Hi, thanks for you interest in our work. You could try reducing the mini batch size or maximum length to decrease memory requirement, this should not result in a siginificant performance drop. You could also try to avoid 4-bit quantization as it slows down the training a bit:)

**Comment by michelle1223** [comment]
Hi,
Sorry but I have another question: Do you mean the "llm_max_text_len" argument in config.py by "maximum length"? If so, may I ask why the default value for llm_max_text_len is set as 1536? Also, do you mean "lora_micro_batch_size" by "mini batch size"? Thanks a lot for your help.

**Comment by Yueeeeeeee** [comment]
Yes, that means the maximum length for LLM training, and you can set it to 2048 or above for better performance. Meanwhile, lora_micro_batch_size is per device mini batch size, that is the batch size used in each forward passing.

**Comment by michelle1223** [comment]
Sorry but could you explain whose length `llm_max_test_len` controls exactly? Does it control the length of the prompt input for the LLM ranker? Also, do you have any suggestions for the minimum of its value? My expected training time is still pretty long for smaller values like 512, so I wonder if it is okay to reduce more.
